Repository sngular/kloadgen, pull requests merged in 2021-08, with the labels that each got.

#109 #108 Make master green again
  pom.xml
  src/main/java/net/coru/kloadgen/sampler/KafkaConsumerSampler.java
Labels: bug

#106 #105 refactor and improve the random tool
  pom.xml
  src/main/java/net/coru/kloadgen/config/valuefiledeserialized/ValueFileDeserializedConfigElement.java
  src/main/java/net/coru/kloadgen/extractor/extractors/AvroExtractor.java
  src/main/java/net/coru/kloadgen/processor/AvroSchemaProcessor.java
  src/main/java/net/coru/kloadgen/processor/JsonSchemaProcessor.java
  src/main/java/net/coru/kloadgen/randomtool/generator/AvroGeneratorTool.java
  src/main/java/net/coru/kloadgen/randomtool/generator/StatelessGeneratorTool.java
  src/main/java/net/coru/kloadgen/randomtool/random/RandomArray.java
  src/main/java/net/coru/kloadgen/randomtool/random/RandomMap.java
  src/main/java/net/coru/kloadgen/randomtool/random/RandomObject.java
  src/main/java/net/coru/kloadgen/randomtool/util/ValidTypeConstants.java
  src/main/java/net/coru/kloadgen/randomtool/util/ValueUtils.java
  src/main/java/net/coru/kloadgen/sampler/KafkaConsumerSampler.java
  src/main/java/net/coru/kloadgen/sampler/KafkaSchemaSampler.java
  src/main/java/net/coru/kloadgen/sampler/SamplerUtil.java
  src/main/java/net/coru/kloadgen/serializer/AvroDeserializer.java
  src/main/java/net/coru/kloadgen/util/PropsKeysHelper.java
  src/main/java/net/coru/kloadgen/util/RandomTool.java
  src/main/java/net/coru/kloadgen/util/StatelessRandomTool.java
  src/test/java/net/coru/kloadgen/randomtool/generator/AvroGeneratorToolTest.java
  src/test/java/net/coru/kloadgen/randomtool/generator/StatelessGeneratorToolTest.java
  src/test/java/net/coru/kloadgen/randomtool/random/RandomArrayTest.java
  src/test/java/net/coru/kloadgen/randomtool/random/RandomMapTest.java
  src/test/java/net/coru/kloadgen/randomtool/random/RandomObjectTest.java
  src/test/java/net/coru/kloadgen/sampler/ConsumerTest.java
  src/test/java/net/coru/kloadgen/util/RandomToolTest.java
Labels: enhancement

#115 #114 Test pom for publish in github
  pom-github.xml
Labels: enhancement

#116 #114 add deliverable configuration
  pom-github.xml
  pom.xml
Labels: help wanted
