Repository sngular/kloadgen, pull requests merged in 2022-04, with the labels that each got.

#202 Develop wiki - Installation
  docs/installation.md
Labels: documentation

#206 Knowledge center module
  docs/_Sidebar.md
  docs/example-test-plan.md
  docs/how-to-run.md
  docs/images/example-test-plan.png
Labels: documentation

#209 #208 sequence and defaults
  pom-maven-central.xml
  pom.xml
  src/main/java/net/coru/kloadgen/randomtool/generator/AvroGeneratorTool.java
  src/test/java/net/coru/kloadgen/processor/JsonSchemaProcessorTest.java
  src/test/java/net/coru/kloadgen/randomtool/generator/AvroGeneratorToolTest.java
Labels: bug

#203 Develop wiki - Configuration
  docs/_Sidebar.md
  docs/about.md
  docs/consumer-configuration.md
  docs/producer-configuration.md
  docs/schemas.md
Labels: documentation

#210 Maven central update
  docs/installation.md
Labels: documentation

#211 Minor changes pre final review
  docs/_Sidebar.md
  docs/about.md
  docs/example-test-plan.md
  docs/getting-started.md
  docs/how-to-run.md
  docs/producer-configuration.md
  docs/release-notes.md
  docs/schemas.md
Labels: documentation

#213 #212 Create a new template issue
  .github/ISSUE_TEMPLATE/documentation_issue.yaml
  pom-maven-central.xml
  pom.xml
Labels: documentation

#219 #218 Apply CorunetStyles to avsc test files
  pom-maven-central.xml
  pom.xml
  src/main/java/net/coru/kloadgen/common/SchemaTypeEnum.java
  src/main/java/net/coru/kloadgen/config/valueserialized/ValueSerializedConfigElementBeanInfo.java
  src/main/java/net/coru/kloadgen/extractor/extractors/AvroExtractor.java
  src/main/java/net/coru/kloadgen/extractor/extractors/ProtoBufExtractor.java
  src/main/java/net/coru/kloadgen/extractor/impl/SchemaExtractorImpl.java
  src/main/java/net/coru/kloadgen/loadgen/impl/ProtobufLoadGenerator.java
  src/main/java/net/coru/kloadgen/model/FieldValueMapping.java
  src/main/java/net/coru/kloadgen/model/json/ArrayField.java
  src/main/java/net/coru/kloadgen/model/json/MapField.java
  src/main/java/net/coru/kloadgen/model/json/ObjectField.java
  src/main/java/net/coru/kloadgen/model/json/Schema.java
  src/main/java/net/coru/kloadgen/processor/ProtobufSchemaProcessor.java
  src/main/java/net/coru/kloadgen/processor/SchemaProcessorLib.java
  src/main/java/net/coru/kloadgen/property/editor/FileSubjectPropertyEditor.java
  src/main/java/net/coru/kloadgen/property/editor/KeyDeserializerPropertyEditor.java
  src/main/java/net/coru/kloadgen/randomtool/random/RandomArray.java
  src/main/java/net/coru/kloadgen/randomtool/random/RandomObject.java
  src/main/java/net/coru/kloadgen/randomtool/util/ValueUtils.java
  src/main/java/net/coru/kloadgen/sampler/SamplerUtil.java
  src/test/resources/avro-files/testNullOnOptionalFields.avsc
  src/test/resources/avro-files/testOptionalMap.avsc
Labels: enhancement

#220 #216 change is parent required parameter
  pom-maven-central.xml
  pom.xml
  src/main/java/net/coru/kloadgen/extractor/extractors/AvroExtractor.java
  src/main/java/net/coru/kloadgen/extractor/extractors/JsonExtractor.java
  src/main/java/net/coru/kloadgen/extractor/extractors/ProtoBufExtractor.java
  src/main/java/net/coru/kloadgen/model/FieldValueMapping.java
  src/main/java/net/coru/kloadgen/processor/AvroSchemaProcessor.java
  src/main/java/net/coru/kloadgen/processor/JsonSchemaProcessor.java
  src/main/java/net/coru/kloadgen/processor/ProtobufSchemaProcessor.java
  src/test/java/net/coru/kloadgen/processor/fixture/JsonSchemaFixturesConstants.java
Labels: enhancement

#231 Rename image files
  docs/consumer-configuration.md
  docs/images/kafka-consumer-properties.png
  docs/images/kafka-header-config-element.png
  docs/images/kafka-producer-properties.png
  docs/images/key-plain-load-generator-config.png
  docs/images/key-schema-load-generator-config.png
  docs/images/kloadgen.png
  docs/images/schema-registry-config.png
  docs/images/schema-registry-success.png
  docs/images/sequence-generator.png
  docs/images/value-schema-deserialization-config.png
  docs/images/value-schema-file-deserialization-config.png
  docs/images/value-schema-file-load-generator-config.png
  docs/images/value-schema-load-generator-config.png
  docs/producer-configuration.md
  docs/schemas.md
Labels: documentation

#225 Include test results screenshots
  docs/images/load_test_process_1.png
  docs/images/load_test_process_2.png
  docs/images/load_test_results.png
Labels: documentation

#226 Sequence requirement removed
  docs/images/sequence-generator.png
  docs/schemas.md
Labels: documentation

#233 Fixes typo
  docs/how-to-run.md
Labels: documentation

#232 Update release notes
  docs/release-notes.md
Labels: documentation

#234 References to contributing guidelenes removed
  docs/additional-information.md
Labels: documentation
