Repository sngular/kloadgen, pull requests merged in 2022-06, with the labels that each got.

#257 #255 Protobuf issue with Date and Time parameterization
  pom-maven-central.xml
  pom.xml
  src/main/java/net/coru/kloadgen/processor/ProtobufSchemaProcessor.java
  src/main/java/net/coru/kloadgen/randomtool/random/RandomObject.java
  src/main/java/net/coru/kloadgen/randomtool/util/ValidTypeConstants.java
  src/test/java/net/coru/kloadgen/processor/ProtobufSchemaProcessorTest.java
  src/test/resources/proto-files/dateTimeTest.proto
Labels: bug

#260 #259 release all versions
  .github/workflows/maven-central-push.yml
  pom-maven-central.xml
  pom.xml
Labels: enhancement

#261 #258 documentation date time
  docs/producer-configuration.md
  docs/schemas.md
  pom-maven-central.xml
  pom.xml
Labels: documentation

#269 #268 Update description. Move checkstyle config file.
  OSS_checkstyle.xml
  config/OSS_style_idea.xml
  pom-maven-central.xml
  pom.xml
Labels: documentation
